FitnessFunction = @simple_fitness;
numberOfVariables = 1;
options = optimoptions(@ga,...
'display','iter', ...
'PlotFcn',@gaplotbestf, ...
'CrossoverFraction',0.8,...
%'MaxStallGenerations',20, ...
'MutationFcn',{@mutationgaussian,1,.8}, ...
%'MaxGenerations', 20, ...
'PopulationSize', 50);
IntCon = [1];
[x,fval] = ga(FitnessFunction,numberOfVariables,[],[],[],[],0,1023,[], IntCon, options);
disp(x);
disp(fval);